### ISSUE TITLE
Link to github in footer

### ISSUE THREAD

**Issue by antonykamp** [entel-me/entel#38]
The link to this Github project in the footer isn't working at the moment.

**Comment by antonykamp** [comment]
Does any of you @malckier @Till-B is working/is going to work on this issue? Otherwise, I would fix it tm to improve our digital representation ;)

**Comment by malckier** [comment]
I've not planned on working anything yet except seeing about getting the mailer going. Then if I still have some time, I'll look into jumping on something.

**Comment by malckier** [comment]
I've not gotten far due to trying to debug. I kicked off w/VSCode debug but it doesn't seem to honor breakpoints. The last project I worked with, had .map files generated by webpack. I was able to set breakpoints through the dev console. How are you debugging? Sorry for the noob question. There's more I can help out on, I just have to get the environment down.

**Comment by antonykamp** [comment]
> How are you debugging? 

funny story :D `console.log()` is our friend at the moment. And I've added a ***_simple_*** debugger in blitz-js/legacy-framework#849. 

> Sorry for the noob question

I have to admit that I had to do some research to answer your question because I'm new to this typescript-react-blitz-world too :) (-> no noob question in this project)

You can use the node-debugger if you run the application with `blitz dev --inspect` (https://github.com/blitz-js/legacy-framework/issues/919, https://github.com/blitz-js/blitz/pull/1063). With this information, I recommend the following tutorial:

https://dev.to/vvo/5-steps-to-debugging-next-js-node-js-from-vscode-or-chrome-devtools-497o 

BUT I tried this for myself, and I'm not satisfied: You debug the compiled JS- code, and I could not see through there yet :/

**Comment by malckier** [comment]
Thanks for the link, but I got it going. I used `blitz dev --inspect` to kick off the app and in VSCode I created `launch.json`.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach  Entel",
            "skipFiles": ["<node_internals>/**"],
            "cwd": "${workspaceFolder}",
            "address": "localhost"
        }
    ]
}
```
