### ISSUE TITLE
Initial DB Issues

### ISSUE THREAD

**Issue by malckier** [entel-me/entel#53]
- `npm run predev` failed to run at first because there was no `./.env.local` file. I copied the `.env` over to `./.env.local` and it did set up docker it seemed.

- Had this error trying to signup: 
Invalid `prisma.user.create()` invocation:

  error: Environment variable not found: DATABASE_URL.

Thanks for your time.

**Comment by antonykamp** [comment]
Hey malckier,

That's a good point!  Thank you! 
We should mention in `README.md` how to set up the project. Because we use [blitzjs](blitzjs.com/) you have to prepare some things, like setting up environment variables in `.env.local` and `.env.test.local` (the missing `DATABASE_URL`) and migrating the database. I'll add this tomorrow and reach out!

**Comment by antonykamp** [comment]
I've added some instructions to README.md :) While the PR isn't closed, you can find the guide here:

https://github.com/antonykamp/entel/blob/readme-setup-instructions/README.md

Feedback is welcome :)

**Comment by malckier** [comment]
That helped in getting things running! I added the DATABASE & MAIL settings in .env.local and .env.test.local. This allowed me to log in and create a couple of lists.

You state "Afterward, you call them with process.env.."  I'm not sure what is meant by this. 

I'm just curious about the mail variables. Is this for filler or does the privateemail.com have an smtp service that you're using?

**Comment by antonykamp** [comment]
> You state "Afterward, you call them with process.env.." I'm not sure what is meant by this.

In typescript, you can access environment variables with `process.env.`. Let's take the [`forgotPasswordMailer.tsx`](https://github.com/entel-me/entel/blob/1f352942b6f9cec4aabad566766f752c4c3c82f5/mailers/forgotPasswordMailer.ts#L22) as an example: You specify your email address in `.env.local` with

```txt
MAIL_MAIL=malckier@malckier.com
```
and now you can access this variable with `process.env.MAIL_MAIL` :)



> I'm just curious about the mail variables.

`mail.privateemail.com`  is the SMTP service of [namecheap mails](https://www.namecheap.com/support/knowledgebase/article.aspx/1179/2175/general-private-email-configuration-for-mail-clients-and-mobile-devices/) :D And [nodemailer](https://nodemailer.com/about/) needs the server name, mail, and password only to send mails :)
